name: get_jadwal
description: Get Jadwal With Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  get: ^4.6.5
  get_storage: ^2.0.3
  dartz: ^0.10.1
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.5
  intl: ^0.17.0

  flutter:
    sdk: flutter

  flutter_driver:
    sdk: flutter
  test: any

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
